services:
  node0:
    image: ros:jazzy-ros-base
    container_name: talker
    command: bash -c "echo 'source /opt/ros/jazzy/setup.bash' >> ~/.bash_profile && exec bash"
    stdin_open: true
    tty: true
    volumes:
      - ./talker_pkg:/NNUF:rw
    working_dir: /NNUF
    networks:
      - node_network

  node1:
    depends_on:
      - node0
    image: ros:jazzy-ros-base
    container_name: listener
    command: bash -c "echo 'source /opt/ros/jazzy/setup.bash' >> ~/.bash_profile && exec bash"
    stdin_open: true
    tty: true
    volumes:
      - ./listener_pkg:/NNUF:rw
    working_dir: /NNUF
    networks:
      - node_network

networks:
  node_network:
    driver: bridge
